build-job:
  stage: build
  script:
    - mkdir -p objects
    - make main
    - make test

test-job1:
  stage: test
  script:
    - mkdir -p objects
    - make main
    - make test
    - ./test
    
test-job2:
  stage: test
  script:
    - mkdir -p objects
    - make main
    - make test_base
    - ./test_base

